### ISSUE TITLE
bgp: ipv4 unicast NRLI sanity checking

### ISSUE THREAD

**Issue by taspelund** [oxidecomputer/maghemite#210]
Add sanity checks for the contents of IPv6 Unicast NLRI, i.e. making sure they only contain valid unicast addresses.

Ranges to drop as invalid:

IPv4:
- 127.0.0.0/8
- 224.0.0.0/4
- 240.0.0.0/4
- 169.254.0.0/16 (optional, as this range is sometimes used as loopback ranges similar to RFC 1918)

**Comment by rcgoodfellow** [comment]
One more check would be to make sure we don't get an NLRI whose next-hop is itself.
e.g.
10.0.0.1/32 via 10.0.0.1

**Comment by rcgoodfellow** [comment]
Moved IPv6 part of this ticket to #211
