### ISSUE TITLE
Building mgd on macOS with `--no-default-features` stopped working

### ISSUE THREAD

**Issue by david-crespo** [oxidecomputer/maghemite#234]
As of https://github.com/oxidecomputer/maghemite/commit/8207cb9c I can't build maghemite on macOS anymore.

```
$ cargo build --no-default-features --bin mgd

.........

error: cannot find macro `compile_fail` in this scope
   --> /Users/david/.cargo/git/checkouts/netadm-sys-25ac2db9b1b244c6/1d75565/libnet/src/sys.rs:703:13
    |
703 |             compile_fail!("only linux and illumos are currently supported")
    |             ^^^^^^^^^^^^

   Compiling ciborium-ll v0.2.2
error[E0412]: cannot find type `ioc_t` in this scope
  --> /Users/david/.cargo/git/checkouts/netadm-sys-25ac2db9b1b244c6/1d75565/libnet/src/sys.rs:54:20
   |
54 | pub const DLD_IOC: ioc_t = 0x0D1D;
   |                    ^^^^^ not found in this scope
```

I think this is because a dependency on `libnet` was added to `mg-common`. It seems designed to be left out of non-illumos builds, but the dependency on libnet is not wrapped in a default feature.

https://github.com/oxidecomputer/maghemite/blob/77246a4e07c86782313184cd1aa73bd2d162db70/mg-common/src/nexus.rs#L99-L116

Maybe I'm misunderstanding how this is supposed to work, because this change did not fix it.

```diff
diff --git a/mg-common/Cargo.toml b/mg-common/Cargo.toml
index 5f3abcc..9101b6c 100644
--- a/mg-common/Cargo.toml
+++ b/mg-common/Cargo.toml
@@ -19,4 +19,7 @@ oximeter.workspace = true
 backoff.workspace = true
 smf.workspace = true
 uuid.workspace = true
-libnet.workspace = true
+libnet = { workspace = true, optional = true }
+
+[features]
+default = ["libnet"]
```

**Comment by rcgoodfellow** [comment]
This will be fixed in #199 with help from oxidecomputer/netadm-sys#27

**Comment by david-crespo** [comment]
Great, and that also gives me a workaround for now to get `mgd` built, and I was able to get Nexus integration tests running locally with that.

```diff
diff --git a/Cargo.toml b/Cargo.toml
index 79dfe01..7465387 100644
--- a/Cargo.toml
+++ b/Cargo.toml
@@ -57,7 +57,7 @@ serde_repr = "0.1"
 anyhow = "1.0.82"
 hyper = "0.14.28"
 serde_json = "1.0.116"
-libnet = { git = "https://github.com/oxidecomputer/netadm-sys", branch = "main" }
+libnet = { git = "https://github.com/oxidecomputer/netadm-sys", branch = "compile-macos" }
 percent-encoding = "2.3.1"
 reqwest = { version = "0.11", features = ["json", "stream", "rustls-tls"] }
 progenitor = { git = "https://github.com/oxidecomputer/progenitor", branch = "main" }
```

Oddly I seem to have to put the 1 back here to get it to discover a port, unless that's a spurious port and it just happens to work (which is probably fine for my purposes because what I'm working on is orthogonal).

https://github.com/oxidecomputer/omicron/blob/bca1f2d63b70e71aef509b94e190e54c6eb3a6be/test-utils/src/dev/maghemite.rs#L139-L140

**Comment by rcgoodfellow** [comment]
Yeah, I have something to that effect in the Omicron PR that is bringing in #199 

https://github.com/oxidecomputer/omicron/pull/5649/files#diff-1ae22ee3c1a09097ae181480040c2841085e82d3cc1ef71257ff080432532cd7L140
