### ISSUE TITLE
DDM's Oximeter producer server should use DNS to find Nexus

### ISSUE THREAD

**Issue by bnaecker** [oxidecomputer/maghemite#304]
DDM's Oximeter producer server currently registers with Nexus in the following snippet:

https://github.com/oxidecomputer/maghemite/blob/ef0edbbf3cf7b3f832e96901dd97282eb9b18cc7/ddm/src/oxstats.rs#L300-L309

Importantly, that looks up Nexus _once_ and then continues to use that resolved address perpetually for metric registration and the periodic re-registration. That should use DNS instead, which would ensure that DDM continues to renew its producer lease even as Nexus instances are reconfigured and moved around.

**Comment by rcgoodfellow** [comment]
Note that `mgd` has more or less this same bit of code as well

https://github.com/oxidecomputer/maghemite/blob/ef0edbbf3cf7b3f832e96901dd97282eb9b18cc7/mgd/src/oxstats.rs#L773-L782

**Comment by bnaecker** [comment]
Sweet, we'll make both use DNS at the same time, thanks Ry.
