### ISSUE TITLE
bgp: implement unacceptable hold time notification

### ISSUE THREAD

**Issue by rcgoodfellow** [oxidecomputer/maghemite#97]
If a peer sends a hold time in an open message that will not work with our keepalive rate, we need to send an unacceptable hold time notification.

**Comment by taspelund** [comment]
@rcgoodfellow it looks like you addressed this earlier in the year in the OxPop PR: https://github.com/oxidecomputer/maghemite/pull/199/files#diff-0a75dc30d679a06f79c68f86c797a951fdfd39713b6752623502069517633510R1610

Are we okay to close out this issue?

**Comment by rcgoodfellow** [comment]
yup
